import 'dart:convert';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/material.dart' hide Radio;
import 'package:http/http.dart' as http;
import 'package:islami/app_colors.dart';
import 'package:islami/home/radio/radio_item.dart';
import 'package:islami/home/radio/radio_model.dart';
import 'package:provider/provider.dart';

import '../../providers/app_config_provider.dart';

class RadioTab extends StatelessWidget {
  final player = AudioPlayer();

  @override
  Widget build(BuildContext context) {
    var provider = Provider.of<AppConfigProvider>(context);

    return FutureBuilder(
      future: getRadio(),
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          var radios = snapshot.data?.radios ?? [];
          return Column(
            children: [
              Expanded(
                flex: 6,
                child: Image.asset('assets/images/radio_image.png'),
              ),
              Text(
                'اذاعة القران الكريم',
                style: Theme.of(context).textTheme.bodyLarge!.copyWith(
                  color:
                      provider.isDarkMode()
                          ? AppColors.whiteColor
                          : AppColors.blackColor,
                ),
              ),
              SizedBox(height: 20),
              SizedBox(
                height: MediaQuery.sizeOf(context).height * .3,

                child: ListView.builder(
                  scrollDirection: Axis.horizontal,

                  physics: PageScrollPhysics(),
                  itemCount: radios.length,
                  itemBuilder: (context, index) {
                    return RadioItem(radio: radios[index], audioPlayer: player);
                  },
                ),
              ),
            ],
          );
        } else if (snapshot.hasError) {
          Text(snapshot.error.toString());
        }
        return Center(
          child: CircularProgressIndicator(color: AppColors.primaryLightColor),
        );
      },
    );
  }

  Future<Autogenerated> getRadio() async {
    var url = Uri.parse('https://mp3quran.net/api/v3/radios');
    var response = await http.get(url);
    if (response.statusCode == 200) {
      var bodyString = response.body;
      var json = jsonDecode(bodyString);
      return Autogenerated.fromJson(json);
    } else {
      throw Exception('faild to load radios');
    }
  }
}
